<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">searchString</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCklEYXRhQ3Vyc29yIHBpcGVsaW5lQ3Vyc29yID0gcGlwZWxpbmUuZ2V0Q3Vy
c29yKCk7DQoJU3RyaW5nCXZhbHVlU3RyaW5nID0gSURhdGFVdGlsLmdldFN0cmluZyggcGlwZWxp
bmVDdXJzb3IsICJ2YWx1ZVN0cmluZyIgKTsNCglTdHJpbmcJc2VhcmNoU3RyaW5nID0gSURhdGFV
dGlsLmdldFN0cmluZyggcGlwZWxpbmVDdXJzb3IsICJzZWFyY2hTdHJpbmciICk7DQpwaXBlbGlu
ZUN1cnNvci5kZXN0cm95KCk7DQoNCgkNCmJvb2xlYW4gaXNGb3VuZCA9IHZhbHVlU3RyaW5nLmNv
bnRhaW5zKHNlYXJjaFN0cmluZyk7CQ0KIA0KDQoNCi8vIHBpcGVsaW5lDQpJRGF0YUN1cnNvciBw
aXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJRGF0YVV0aWwucHV0KCBw
aXBlbGluZUN1cnNvcl8xLCAiaXNGb3VuZCIsIGlzRm91bmQgKTsNCnBpcGVsaW5lQ3Vyc29yXzEu
ZGVzdHJveSgpOw0KCQ==</value>
</Values>
