<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">getTriggerFilter</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUKSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJz
b3IoKTsKCVN0cmluZwl0cmlnZ2VyTmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5l
Q3Vyc29yLCAidHJpZ2dlck5hbWUiICk7CnBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsKCklEYXRh
W10gdHJpZ2dlckNvbmRpdGlvbnMgPSBudWxsOwkJCgpUcmlnZ2VyTWFuYWdlbWVudFV0aWwgdG11
ID0gbmV3IFRyaWdnZXJNYW5hZ2VtZW50VXRpbCh0cmlnZ2VyTmFtZSk7CQkKdHJpZ2dlckNvbmRp
dGlvbnMgPSB0bXUuZ2V0Q29uZGl0aW9uc0FzRGF0YSgpOwkJCQoKCi8vIHBpcGVsaW5lCklEYXRh
Q3Vyc29yIHBpcGVsaW5lQ3Vyc29yXzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsKCklEYXRhVXRp
bC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJ0cmlnZ2VyRmlsdGVycyIsIHRyaWdnZXJDb25kaXRp
b25zICk7CnBpcGVsaW5lQ3Vyc29yXzEuZGVzdHJveSgpOwoKCgoJ</value>
</Values>
